version: '3'

services:
  mercure:
    image: dunglas/mercure
    container_name: mercure
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      # Uncomment the following line to disable HTTPS
#      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'poc-mercure' #${MERCURE_PUBLISHER_JWT_KEY}
      MERCURE_SUBSCRIBER_JWT_KEY: 'poc-mercure' #${MERCURE_SUBSCRIBER_JWT_KEY}
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins https://127.0.0.1:8081 https://localhost:8081
    # Uncomment the following line to enable the development mode
    #command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - mercure_data:/data
      - mercure_config:/config

volumes:
  mercure_data:
  mercure_config:
